apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  selector:
    matchLabels:
      app: todo
  replicas: 3
  template:
    metadata:
      labels:
        app: todo
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      containers:
        - name: todo-service
          image: gcr.io/sensys/todo:develop_latest # to be change
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "6666"
            - name: HOST
              value: "0.0.0.0"
            - name: ENV
              value: "development"
          ports:
            - name: grpc
              containerPort: 6666
          resources:
            requests:
              cpu: 5m
              memory: 15Mi
            limits:
              cpu: 50m
              memory: 150Mi
          securityContext:
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true