apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    name: todo-service
spec:
  selector:
    name: todo-service
  ports:
    - port: 6666
      name: grpc
      targetPort: 6666
